/*
 * Auto-generated by Frida. Please modify to match the signature of LoadLibraryW.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    try {
      var path = args[0].readUtf16String();
      log('LoadLibraryW("' + path + '")');
    } catch(e) {}
  },

  onLeave(log, retval, state) {
  }
});
