#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
install_script="$script_dir/install-service.sh"

grep -Fq 'systemctl enable quote-netzip-rs-supplement.service' "$install_script"
grep -Fq 'systemctl restart quote-netzip-rs-supplement.service' "$install_script"
grep -Fq 'systemctl stop quote-netzip-rs-full-push.service' "$install_script"
grep -Fq 'systemctl is-active --quiet quote-netzip-rs-supplement.service' "$install_script"
grep -Fq 'quote-netzip-rs-full-push.service' "$install_script"
grep -Fq 'quote-netzip-rs-full-push.timer' "$install_script"
grep -Fq 'systemctl enable quote-netzip-rs-full-push.service' "$install_script"
grep -Fq 'systemctl restart quote-netzip-rs-full-push.service' "$install_script"
grep -Fq 'systemctl is-active --quiet quote-netzip-rs-full-push.service' "$install_script"
grep -Fq 'NETZIP_INSTALL_ENABLE_FULL_PUSH' "$install_script"
grep -Fq 'legacy_install_binary="$install_dir/netzip_service"' "$install_script"
grep -Fq 'mv -f "$legacy_install_binary" "$legacy_install_binary.retired"' "$install_script"
grep -Fq 'systemctl disable --now netzip-rs-full-push.timer netzip-rs-full-push.service' "$install_script"
grep -Fq 'systemctl disable --now netzip-rs.service' "$install_script"
grep -Fq 'systemctl disable --now netzip-full-push.timer' "$install_script"
grep -Fq 'Environment=NETZIP_SERVICE_LISTEN=0.0.0.0:16893' "$script_dir/../deploy/quote-netzip-rs-supplement.service"
grep -Fq 'Environment=MALLOC_ARENA_MAX=4' "$script_dir/../deploy/quote-netzip-rs-supplement.service"
grep -Fq 'NETZIP_SERVICE_ADDR:-127.0.0.1:16893' "$script_dir/run-full-push.sh"
grep -Fq 'NETZIP_FULL_PUSH_WORKERS:-64' "$script_dir/run-full-push.sh"
grep -Fq 'http://127.0.0.1:16893/health' "$install_script"
grep -Fq 'Restart=always' "$script_dir/../deploy/quote-netzip-rs-full-push.service"
grep -Fq 'WantedBy=multi-user.target' "$script_dir/../deploy/quote-netzip-rs-full-push.service"
test ! -e "$script_dir/../deploy/quote-netzip-rs-full-push.timer"
! grep -Fq 'systemctl enable --now quote-netzip-rs-full-push.timer' "$install_script"
stop_line="$(grep -nF 'systemctl stop quote-netzip-rs-full-push.service' "$install_script" | cut -d: -f1)"
restart_main_line="$(grep -nF 'systemctl restart quote-netzip-rs-supplement.service' "$install_script" | cut -d: -f1)"
restart_push_line="$(grep -nF 'systemctl restart quote-netzip-rs-full-push.service' "$install_script" | cut -d: -f1)"
test "$stop_line" -lt "$restart_main_line"
test "$restart_main_line" -lt "$restart_push_line"
! grep -Fq '18083' "$script_dir/../deploy/quote-netzip-rs-supplement.service"
! grep -Fq '18083' "$script_dir/run-full-push.sh"
